# Generated by Django 4.0.5 on 2022-06-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='User',
        ),
    ]
